"""empty message

Revision ID: e3cd25423c4e
Revises: 914d24306559
Create Date: 2023-08-21 13:13:16.751710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cd25423c4e'
down_revision = '914d24306559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mega_sena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrecadacao_total', sa.String(), nullable=True))
        batch_op.alter_column('data_do_sorteio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('bola1',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bola2',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bola3',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bola4',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bola5',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bola6',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ganhadores_6_acertos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cidade_uf',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('rateio_6_acertos',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ganhadores_5_acertos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rateio_5_acertos',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ganhadores_4_acertos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rateio_4_acertos',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('acumulado_6_acertos',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('estimativa_premio',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('acumulado_sorteio_especial_mega_da_virada',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('observacao',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('arrecadao_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mega_sena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrecadao_total', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('observacao',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('acumulado_sorteio_especial_mega_da_virada',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('estimativa_premio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('acumulado_6_acertos',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('rateio_4_acertos',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ganhadores_4_acertos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rateio_5_acertos',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ganhadores_5_acertos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rateio_6_acertos',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cidade_uf',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ganhadores_6_acertos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola6',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola5',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola4',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola3',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola2',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('bola1',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('data_do_sorteio',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('arrecadacao_total')

    # ### end Alembic commands ###
